image: maven:3.9-eclipse-temurin-21

stages:
  - validate
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

# YAML anchor for Maven job template
.maven_template: &maven_template
  before_script:
    - cd $PROJECT_DIR
  artifacts:
    paths:
      - $PROJECT_DIR/target
    expire_in: 3 hours

validate:
  stage: validate
  parallel:
    matrix:
      - PROJECT_DIR: backend
      - PROJECT_DIR: frontend
  <<: *maven_template
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  parallel:
    matrix:
      - PROJECT_DIR: backend
      - PROJECT_DIR: frontend
  <<: *maven_template
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.main.skip=true test

package:
  stage: package
  parallel:
    matrix:
      - PROJECT_DIR: backend
      - PROJECT_DIR: frontend
  <<: *maven_template
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.main.skip=true -Dmaven.test.skip=true package
  artifacts:
    paths:
      - $PROJECT_DIR/target/*.jar

deploy-to-test-server:
  stage: deploy
  script:
    - 'true'

deploy-to-production:
  stage: deploy
  script:
    - 'true'
  only:
    - master
